Project TelegramBot {
  database_type: ''
  Note: ''
}

Table users {
  id int [pk, not null]
  Name varchar[not null]
  Phone int [not null]
  Payment Method varchar [not null, default:PayNow]
}

Table payment {
  id int [not null] // ZK
  request_from int [not null] // JJ
  amount int [not null] // $10...
  completed bool [not null, default:false]
  eventid varchar [not null]
  payload varchar [not null]
}

Table event{
  user_id int [not null]
  startdate date [not null]
  title varchar [not null]
  completed bool [not null, default:false]
}

Ref: payment.user_id > userProfile.user_id  