Project TelegramBot {
  database_type: ''
  Note: ''
}

Table user {
  id int [pk, not null]
  name varchar [not null]
  phone int [not null]
  payment varchar [not null, default:"PayNow"]
}

Table payment {
  id int [not null] // ZK
  request_from int [not null] // JJ
  amount int [not null] // $10...
  completed bool [not null, default:false]
  eventid varchar [not null]
  payload varchar [not null]
}

Table event{
  id int [not null]
  startdate date [not null]
  title varchar [not null]
  userid int [not null]
  completed bool [not null, default:false]
}

Ref: payment.id > user.id  
Ref: payment.request_from > user.id 
Ref: payment.eventid > event.id
Ref: event.userid > user.id  