Project TelegramBot {
  database_type: ''
  Note: ''
}

Table userProfile {
  id int [pk, not null]
  phone int [not null]
  paymentMethod varchar [not null, default:PayNow]
}

Table payment {
  id varchar [..] // ZK
  request_from varchar [] // JJ
  amount int [] // $10...
  completed bool [not null, default:false]
  eventid 
}

Table event{
  id varchar [pk, not null]
  startdate date [not null]
  title varchar [not null]
}

Ref: payment.user_id > userProfile.user_id  